package cn.edu.cuit.mapper;

import cn.edu.cuit.pojo.HosHasSec;

public interface HosHasSecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hos_has_sec
     *
     * @mbggenerated
     */
    int insert(HosHasSec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hos_has_sec
     *
     * @mbggenerated
     */
    int insertSelective(HosHasSec record);
}