package cn.edu.cuit.mapper;

import cn.edu.cuit.pojo.HospitalHasSectionKey;

public interface HospitalHasSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_has_section
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(HospitalHasSectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_has_section
     *
     * @mbggenerated
     */
    int insert(HospitalHasSectionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_has_section
     *
     * @mbggenerated
     */
    int insertSelective(HospitalHasSectionKey record);
}