package cn.edu.cuit.mapper;

import cn.edu.cuit.pojo.Hospital;
import org.apache.ibatis.annotations.Param;

import java.awt.geom.Area;
import java.util.List;
import java.util.Set;

public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    int insert(Hospital record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    int insertSelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    Hospital selectByPrimaryKey(Integer hid);


    Hospital selectByHos(@Param("id") Integer id,@Param("name") String name);


    /**
     * 医院列表页
     * 根据等级、地区查询医院信息
     * @param rank 等级
     * @param area 地区
     * @return
     */
    List<Hospital> selectByFilter(@Param("rank") String rank,@Param("area") String area,@Param("secId") Integer secId,@Param("hos") String hos);

    /**
     * 搜索
     * 根据条件查询医院信息
     * @param word 搜索关键字（医院）
     * @param area 地区
     * @param rank 等级
     * @return
     */
    List<Hospital>  selectByHosWord(@Param("word") String word,@Param("area") String area, @Param("rank") String rank);

    /**
     * 搜索
     * 根据条件查询医院信息
     * @param word 搜索关键字（科室）
     * @param area 地区
     * @param rank 等级
     * @return
     */
    List<Hospital>  selectBySecWord(@Param("word") String word,@Param("area") String area, @Param("rank") String rank);
    /**
     * 搜索
     * 根据条件查询医院信息
     * @param word 搜索关键字（疾病）
     * @param area 地区
     * @param rank 等级
     * @return
     */

    List<Hospital>  selectBySickWord(@Param("word") String word,@Param("area") String area, @Param("rank") String rank);

    /**
     * 根据地区查询指定医院信息
     * @param area  地区
     * @return
     */
    List<Hospital> selectByArea(@Param("area") String area);

    /**
     * 查询所有医院地区
     * @return 返回所有医院地区
     */
    Set<String> selectAllAddress();

    /**
     * 查询所有医院等级
     * @return 返回所有医院等级
     */
    Set<String> selectRank();

    /**
     * 查询指定数量的医院信息
     * @param num
     * @return
     */
    List<Hospital> selectByNum(@Param("num") int num);

    /**
     * 根据条件查询医院信息
     * @param area 地区
     * @param rank 等级
     * @return
     */

    List<Hospital> selectByTerms(@Param("area") String area,@Param("rank") String rank);



    Hospital selectBySid(Integer id);

    String selectByHname(String hName);

    /**
     * 查询所有医院信息
     * @return
     */
    List<Hospital> selectHos();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Hospital record);


    int upHos(@Param("id") Integer id,@Param("hname") String hname,@Param("harea")String harea, @Param("hadr")String hadr,
              @Param("htell")String htell,@Param("htime")String htime,@Param("hrank")String hrank,@Param("himg")String himg);

}