package cn.edu.cuit.mapper;

import cn.edu.cuit.pojo.Idea;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface IdeaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbggenerated
     */
    int insert(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbggenerated
     */
    int insertSelective(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbggenerated
     */
    Idea selectByPrimaryKey(Integer iid);


    List<Idea> selectIdea();

   int insertIdea(@Param("uid") Integer uid, @Param("idea") String idea, @Param("date") String date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Idea record);
}