package cn.edu.cuit.mapper;

import cn.edu.cuit.pojo.SectionType;

import java.util.List;
import java.util.Set;

public interface SectionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_type
     *
     * @mbggenerated
     */
    int insert(SectionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_type
     *
     * @mbggenerated
     */
    int insertSelective(SectionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_type
     *
     * @mbggenerated
     */
    SectionType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SectionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SectionType record);

    List<SectionType> selectSection();

    List selectByHosId(Integer id);
}