package cn.edu.cuit.mapper;

import cn.edu.cuit.pojo.Section;
import cn.edu.cuit.pojo.Work;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface SectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    int insert(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    int insertSelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     * 根据科室id 查询科室信息
     */
    Section selectByPrimaryKey(Integer sid);

    /**
     * 根据名称查询科室信息
     * @param hos
     * @return
     */

    List<Section> selectByHos(@Param("hos") String hos);

    String selectBySname(String sName);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Section record);

    /**
     * 根据type查找section
     * @param type
     * @return
     */
    List<Section> selectByType(int type);


    List<Section> selectByIdType(@Param("id") Integer id, @Param("type") Integer type);


    List<Section> selectSec();

    /**
     *搜索
     * 根据关键字查询科室id
     * @param word
     * @return
     */

    List<Section> selectByWord(@Param("word") String word);



     int upSec(@Param("id") Integer id,@Param("sname") String sname,@Param("type") String type);
}