package cn.edu.cuit.mapper;

import cn.edu.cuit.pojo.SickType;

import java.util.List;

public interface SickTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_type
     *
     * @mbggenerated
     */
    int insert(SickType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_type
     *
     * @mbggenerated
     */
    int insertSelective(SickType record);

//    查询body字段
    List findBody();
//    根据body查询 其他信息
    List selectByBody(String body);
}