package cn.edu.cuit.mapper;

import cn.edu.cuit.pojo.Sick;

import java.util.List;

public interface SickMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick
     *
     * @mbggenerated
     */
    int insert(Sick record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick
     *
     * @mbggenerated
     */
    int insertSelective(Sick record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick
     *
     * @mbggenerated
     */
    Sick selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sick record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sick record);

//    根据type查询疾病信息
    List selectByType(Integer type);


    int selectByWord(String word);
}