package cn.edu.cuit.mapper;

import cn.edu.cuit.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * 根据邮箱查询用户信息
     * @param email
     * @return
     */
    List<User> selectByEmail(String email);

    /**
     * 根据用户名查询用户信息
     * @param username
     * @return
     */
    List<User> selectByUsername(String username);

    List<User> selectUser();

    /**
     * 用于登录验证（根据用户的输入信息进行查询）
     * @param user
     * @return
     */
    User selectByUser(User user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    /**
     * 用户修改密码
     * @param pass 新密码
     * @param email 邮箱
     * @return
     */

    int updateByEmail(@Param("password") String pass, @Param("email") String email);


    int upUser(@Param("id") Integer id, @Param("uname") String uname,
                     @Param("pass") String pass,@Param("state") String state,@Param("uemail") String uemail);

}