package cn.edu.cuit.pojo;

public class Doctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.did
     *
     * @mbggenerated
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.dname
     *
     * @mbggenerated
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.dsex
     *
     * @mbggenerated
     */
    private String dsex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.hospital_hid
     *
     * @mbggenerated
     */
    private String dtitle;

    private Integer hospitalHid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.section_sid
     *
     * @mbggenerated
     */
    private Integer sectionSid;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.money
     *
     * @mbggenerated
     */
    private String money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.did
     *
     * @return the value of doctor.did
     *
     * @mbggenerated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.did
     *
     * @param did the value for doctor.did
     *
     * @mbggenerated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.dname
     *
     * @return the value of doctor.dname
     *
     * @mbggenerated
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.dname
     *
     * @param dname the value for doctor.dname
     *
     * @mbggenerated
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.dsex
     *
     * @return the value of doctor.dsex
     *
     * @mbggenerated
     */
    public String getDsex() {
        return dsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.dsex
     *
     * @param dsex the value for doctor.dsex
     *
     * @mbggenerated
     */
    public void setDsex(String dsex) {
        this.dsex = dsex == null ? null : dsex.trim();
    }

    public String getDtitle() {
        return dtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.dsex
     *
     * @param dtitle the value for doctor.dsex
     *
     * @mbggenerated
     */
    public void setDtitle(String dtitle) {
        this.dtitle = dtitle == null ? null : dtitle.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.hospital_hid
     *
     * @return the value of doctor.hospital_hid
     *
     * @mbggenerated
     */
    public Integer getHospitalHid() {
        return hospitalHid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.hospital_hid
     *
     * @param hospitalHid the value for doctor.hospital_hid
     *
     * @mbggenerated
     */
    public void setHospitalHid(Integer hospitalHid) {
        this.hospitalHid = hospitalHid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.section_sid
     *
     * @return the value of doctor.section_sid
     *
     * @mbggenerated
     */
    public Integer getSectionSid() {
        return sectionSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.section_sid
     *
     * @param sectionSid the value for doctor.section_sid
     *
     * @mbggenerated
     */
    public void setSectionSid(Integer sectionSid) {
        this.sectionSid = sectionSid;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.money
     *
     * @return the value of doctor.money
     *
     * @mbggenerated
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.money
     *
     * @param money the value for doctor.money
     *
     * @mbggenerated
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }
}