package cn.edu.cuit.pojo;

public class HosHasSec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hos_has_sec.hospital_hid
     *
     * @mbggenerated
     */
    private Integer hospitalHid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hos_has_sec.section_sid
     *
     * @mbggenerated
     */
    private Integer sectionSid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hos_has_sec.hospital_hid
     *
     * @return the value of hos_has_sec.hospital_hid
     *
     * @mbggenerated
     */
    public Integer getHospitalHid() {
        return hospitalHid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hos_has_sec.hospital_hid
     *
     * @param hospitalHid the value for hos_has_sec.hospital_hid
     *
     * @mbggenerated
     */
    public void setHospitalHid(Integer hospitalHid) {
        this.hospitalHid = hospitalHid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hos_has_sec.section_sid
     *
     * @return the value of hos_has_sec.section_sid
     *
     * @mbggenerated
     */
    public Integer getSectionSid() {
        return sectionSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hos_has_sec.section_sid
     *
     * @param sectionSid the value for hos_has_sec.section_sid
     *
     * @mbggenerated
     */
    public void setSectionSid(Integer sectionSid) {
        this.sectionSid = sectionSid;
    }
}