package cn.edu.cuit.pojo;

public class Hospital {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hid
     *
     * @mbggenerated
     */
    private Integer hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hname
     *
     * @mbggenerated
     */
    private String hname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hadr
     *
     * @mbggenerated
     */
    private String hadr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.htell
     *
     * @mbggenerated
     */
    private String htell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.htime
     *
     * @mbggenerated
     */
    private String htime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hrank
     *
     * @mbggenerated
     */
    private String hrank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.himg
     *
     * @mbggenerated
     */
    private String himg;

    private String harea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hid
     *
     * @return the value of hospital.hid
     *
     * @mbggenerated
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hid
     *
     * @param hid the value for hospital.hid
     *
     * @mbggenerated
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hname
     *
     * @return the value of hospital.hname
     *
     * @mbggenerated
     */
    public String getHname() {
        return hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hname
     *
     * @param hname the value for hospital.hname
     *
     * @mbggenerated
     */
    public void setHname(String hname) {
        this.hname = hname == null ? null : hname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hadr
     *
     * @return the value of hospital.hadr
     *
     * @mbggenerated
     */
    public String getHadr() {
        return hadr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hadr
     *
     * @param hadr the value for hospital.hadr
     *
     * @mbggenerated
     */
    public void setHadr(String hadr) {
        this.hadr = hadr == null ? null : hadr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.htell
     *
     * @return the value of hospital.htell
     *
     * @mbggenerated
     */
    public String getHtell() {
        return htell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.htell
     *
     * @param htell the value for hospital.htell
     *
     * @mbggenerated
     */
    public void setHtell(String htell) {
        this.htell = htell == null ? null : htell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.htime
     *
     * @return the value of hospital.htime
     *
     * @mbggenerated
     */
    public String getHtime() {
        return htime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.htime
     *
     * @param htime the value for hospital.htime
     *
     * @mbggenerated
     */
    public void setHtime(String htime) {
        this.htime = htime == null ? null : htime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hrank
     *
     * @return the value of hospital.hrank
     *
     * @mbggenerated
     */
    public String getHrank() {
        return hrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hrank
     *
     * @param hrank the value for hospital.hrank
     *
     * @mbggenerated
     */
    public void setHrank(String hrank) {
        this.hrank = hrank == null ? null : hrank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.himg
     *
     * @return the value of hospital.himg
     *
     * @mbggenerated
     */
    public String getHimg() {
        return himg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.himg
     *
     * @param himg the value for hospital.himg
     *
     * @mbggenerated
     */
    public void setHimg(String himg) {
        this.himg = himg == null ? null : himg.trim();
    }



    public  String getHarea(){ return  harea;}

    public void setHarea(String harea) {
        this.harea = harea == null ? null : harea.trim();
    }

}