package cn.edu.cuit.pojo;

public class Idea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.iid
     *
     * @mbggenerated
     */
    private Integer iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.imsg
     *
     * @mbggenerated
     */
    private String imsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.user_uid
     *
     * @mbggenerated
     */
    private Integer userUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.idate
     *
     * @mbggenerated
     */
    private String idate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.iid
     *
     * @return the value of idea.iid
     *
     * @mbggenerated
     */
    public Integer getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.iid
     *
     * @param iid the value for idea.iid
     *
     * @mbggenerated
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.imsg
     *
     * @return the value of idea.imsg
     *
     * @mbggenerated
     */
    public String getImsg() {
        return imsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.imsg
     *
     * @param imsg the value for idea.imsg
     *
     * @mbggenerated
     */
    public void setImsg(String imsg) {
        this.imsg = imsg == null ? null : imsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.user_uid
     *
     * @return the value of idea.user_uid
     *
     * @mbggenerated
     */
    public Integer getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.user_uid
     *
     * @param userUid the value for idea.user_uid
     *
     * @mbggenerated
     */
    public void setUserUid(Integer userUid) {
        this.userUid = userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.idate
     *
     * @return the value of idea.idate
     *
     * @mbggenerated
     */
    public String getIdate() {
        return idate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.idate
     *
     * @param idate the value for idea.idate
     *
     * @mbggenerated
     */
    public void setIdate(String idate) {
        this.idate = idate == null ? null : idate.trim();
    }
}