package cn.edu.cuit.pojo;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oid
     *
     * @mbggenerated
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.otime
     *
     * @mbggenerated
     */
    private String otime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.stime
     *
     * @mbggenerated
     */
    private String stime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sname
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.dname
     *
     * @mbggenerated
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.hname
     *
     * @mbggenerated
     */
    private String hname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oid
     *
     * @return the value of order.oid
     *
     * @mbggenerated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oid
     *
     * @param oid the value for order.oid
     *
     * @mbggenerated
     */
    public void setOid(Integer oid) {this.oid = oid;}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.otime
     *
     * @return the value of order.otime
     *
     * @mbggenerated
     */
    public String getOtime() {
        return otime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.otime
     *
     * @param otime the value for order.otime
     *
     * @mbggenerated
     */
    public void setOtime(String otime) {
        this.otime = otime == null ? null : otime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.stime
     *
     * @return the value of order.stime
     *
     * @mbggenerated
     */
    public String getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.stime
     *
     * @param stime the value for order.stime
     *
     * @mbggenerated
     */
    public void setStime(String stime) {
        this.stime = stime == null ? null : stime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sname
     *
     * @return the value of order.sname
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sname
     *
     * @param sname the value for order.sname
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.state
     *
     * @return the value of order.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.state
     *
     * @param state the value for order.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.dname
     *
     * @return the value of order.dname
     *
     * @mbggenerated
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.dname
     *
     * @param dname the value for order.dname
     *
     * @mbggenerated
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.hname
     *
     * @return the value of order.hname
     *
     * @mbggenerated
     */
    public String getHname() {
        return hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.hname
     *
     * @param hname the value for order.hname
     *
     * @mbggenerated
     */
    public void setHname(String hname) {
        this.hname = hname == null ? null : hname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.uname
     *
     * @return the value of order.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.uname
     *
     * @param uname the value for order.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }
}