package cn.edu.cuit.pojo;

public class User {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upswd
     *
     * @mbggenerated
     */
    private String upswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uemail
     *
     * @mbggenerated
     */
    private String uemail;
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upswd
     *
     * @return the value of user.upswd
     *
     * @mbggenerated
     */
    public String getUpswd() {
        return upswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upswd
     *
     * @param upswd the value for user.upswd
     *
     * @mbggenerated
     */
    public void setUpswd(String upswd) {
        this.upswd = upswd == null ? null : upswd.trim();
    }

    public String getState() {return state;}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uemail
     *
     * @return the value of user.uemail
     *
     * @mbggenerated
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uemail
     *
     * @param uemail the value for user.uemail
     *
     * @mbggenerated
     */
    public void setUemail(String uemail) {
        this.uemail = uemail == null ? null : uemail.trim();
    }

    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}